# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 服务汇总
    url: post
    weight: 10
  - name: 活动资讯
    identifier: events
    url: events
    weight: 20
  - name: 活动通知
    parent: events
    url: events/new/
    weight: 21
  - name: 往期回顾
    parent: events
    url: events/past/
    weight: 22
  - name: 合作伙伴
    identifier: partners
    url: partners
    weight: 30
  - name: 学联卡
    parent: partners
    url: partners/card/
    weight: 31
  - name: 关于我们
    identifier: about
    url: about
    weight: 40
  - name: 联系我们
    parent: about
    url: about/contact
    weight: 41
