# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 服务汇总
    url: service
    identifier: service
    weight: 10
  - name: 实用信息
    parent: service
    url: service/booklet
    weight: 11
  - name: 新生Q&A
    parent: service
    url: service/qa
    weight: 12
  - name: 活动资讯
    identifier: event
    url: event
    weight: 20
  - name: 活动通知
    parent: event
    url: event/new/
    weight: 21
  - name: 往期回顾
    parent: event
    url: event/past/
    weight: 22
  - name: 合作伙伴
    identifier: partner
    url: partner
    weight: 30
  - name: 商业合作
    parent: partner
    url: partner/business/
    weight: 31
  - name: 学联卡
    parent: partner
    url: partner/card/
    weight: 32
  - name: 关于我们
    identifier: about
    url: about
    weight: 40
  - name: 团队信息
    parent: about
    url: about/people/
    weight: 41
  - name: 部门介绍
    parent: about
    url: about/group/
    weight: 42
  - name: 联系我们
    parent: about
    url: about/contact/
    weight: 43
